# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutt',
            name='author',
            field=models.TextField(),
        ),
    ]
