# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutt',
            name='authorid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
