# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0004_flutt_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flutt',
            old_name='authorid',
            new_name='author_id',
        ),
    ]
